name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  security-events: write
  packages: read
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'java'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven 3.9.2
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
          tar -xzf apache-maven-3.9.2-bin.tar.gz
          sudo mv apache-maven-3.9.2 /usr/local/apache-maven
          echo "MAVEN_HOME=/usr/local/apache-maven" >> $GITHUB_ENV
          echo "PATH=/usr/local/apache-maven/bin:$PATH" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

      - name: Upload CodeQL results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./codeql-results/results.sarif
          category: java-${{ github.run_id }}

      # The rest of your steps follow here...

